### ISSUE TITLE
Missing author in spec

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/rendering-collections-reading#6]
Out of the box, lab gives this error:
```
// ♥ rspec --fail-fast
F

Failures:

  1) navigate shows the title on the show page in a h1 tag
     Failure/Error: <%= @post.author.name %>

     ActionView::Template::Error:
       undefined method `name' for nil:NilClass
     # ./app/views/posts/show.html.erb:1:in `_app_views_posts_show_html_erb___4193817740220770974_70333896062820'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/rack/logger.rb:38:in `call_app'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `block in call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/application.rb:165:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:60:in `process'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:35:in `process_and_follow_redirects'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:21:in `visit'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/rack_test/driver.rb:42:in `visit'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/session.rb:232:in `visit'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/post_spec.rb:10:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `name' for nil:NilClass
     #   ./app/views/posts/show.html.erb:1:in `_app_views_posts_show_html_erb___4193817740220770974_70333896062820'

```

To fix, add and associate an author:
```
#post_spec.rb

  before do
    @author = Author.create(name: "Me", hometown: "The town where I lived.")
    @post = Post.create(title: "My Post", description: "My post desc", author_id: @author.id)
  end
```
But with a more creative name :P

**Comment by AnnJohn** [comment]
thanks @onyoo. We'll look into this, but if possible, could you raise a pull request to correct the specs? if not, of course no problem.

**Comment by onyoo** [comment]
I hope that is what you meant. I don't want to step on anyone's toes.

**Comment by vicfriedman** [comment]
hey @onyoo thanks so much for submitting the pull request. This lab isn't structured in the best way because there isn't a clear way to link author and post. I am removing author from this reading because you can still cover everything about collection partials without them. I'm going to go ahead and close your PR because the scope of the issue was much larger than the PR you submitted. Thank you though!!

**Comment by onyoo** [comment]
@vicfriedman Thanks for the feedback! You guys do an awesome job! ^^
